# Welcome to Numpy Tutorial

In [1]:
import numpy as np

In [2]:
N_array = np.array([[1,2,3],[4,5,6]])

In [3]:
type(N_array)

numpy.ndarray

In [8]:
(N_array)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
N_array1 = np.array([[2,4,6],[9,8,15]])

In [6]:
type(N_array1)

numpy.ndarray

In [7]:
N_array1

array([[ 2,  4,  6],
       [ 9,  8, 15]])

In [10]:
integers = np.array([[1,2,3 ,4],[5,6,7 ,13]])

In [11]:
integers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 13]])

In [12]:
floats = np.array([0.0, 0.10, 0.12,0.3,0.5 ,0.63])

In [13]:
floats

array([0.  , 0.1 , 0.12, 0.3 , 0.5 , 0.63])

In [14]:
integers.ndim

2

In [15]:
floats.ndim

1

In [16]:
integers.shape

(2, 4)

In [17]:
floats.shape

(6,)

In [18]:
integers.size

8

In [19]:
floats.size

6

In [20]:
for row in integers:
    print(row)

[1 2 3 4]
[ 5  6  7 13]


In [21]:
for i in integers.flat:
    print(i, end="")

123456713

In [22]:
for i in integers.flat:
    print(i)

1
2
3
4
5
6
7
13


In [23]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [29]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [33]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [36]:
np.linspace(0,20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [39]:
np.linspace(0,50,num=6)

array([ 0., 10., 20., 30., 40., 50.])

In [40]:
np.arange(1,31).reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [43]:
np.arange(1,31).reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [45]:
np.random.randint(1,20,6)

array([ 9, 12,  4, 11,  7,  7])

In [46]:
rand_array = np.random.randint(1,100,15)

In [47]:
rand_array

array([64, 22, 68, 96, 58, 21, 27, 91, 15, 61, 99, 12,  2, 34, 11])

In [48]:
rand_array.sum()

681

In [49]:
rand_array.mean()

45.4

In [50]:
rand_array.min()

2

In [51]:
rand_array.max()

99

In [52]:
rand_array.std()

32.13471642943189

In [53]:
n1 = np.arange(1,10,2)

In [55]:
n_rand = np.random.randint(1,20,5)

In [56]:
n1

array([1, 3, 5, 7, 9])

In [57]:
n_rand

array([ 5, 17,  6, 10,  8])

In [58]:
n1 + n_rand

array([ 6, 20, 11, 17, 17])

In [59]:
n1 * n_rand

array([ 5, 51, 30, 70, 72])

In [60]:
n1 / 3

array([0.33333333, 1.        , 1.66666667, 2.33333333, 3.        ])

In [61]:
n_rand /3

array([1.66666667, 5.66666667, 2.        , 3.33333333, 2.66666667])

In [62]:
n1 +=5

In [63]:
n_rand +=3

In [64]:
n1 

array([ 6,  8, 10, 12, 14])

In [65]:
n_rand

array([ 8, 20,  9, 13, 11])

In [66]:
np.sqrt(n1)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162, 3.74165739])

In [67]:
np.sqrt(n_rand)

array([2.82842712, 4.47213595, 3.        , 3.60555128, 3.31662479])

In [68]:
s1 = np.arange(1,10,2)
s2 = np.arange(1,11,3)

In [69]:
s1

array([1, 3, 5, 7, 9])

In [70]:
s2

array([ 1,  4,  7, 10])

In [71]:
s1 + s2

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

Indexing and Slicing

In [72]:
n1 = np.random.randint(1,30,8)

In [73]:
n1

array([28, 22, 20, 16, 22, 29, 12, 11])

In [74]:
n1[3]

16

In [75]:
n1[2:7]

array([20, 16, 22, 29, 12])

In [76]:
n1[:3]

array([28, 22, 20])

In [77]:
n1[4:]

array([22, 29, 12, 11])

In [78]:
n2 = np.arange(1,7)

In [79]:
n2

array([1, 2, 3, 4, 5, 6])

In [80]:
n2[:3]

array([1, 2, 3])

In [81]:
n2[:3] = 7

In [82]:
n2

array([7, 7, 7, 4, 5, 6])

In [84]:
n3 = np.random.randint(1,100,20)

In [85]:
n3

array([29, 25, 14, 84, 35, 93, 11, 84, 74, 35, 65, 53, 42, 50, 49,  9, 90,
       87, 36, 97])

In [86]:
n3 = n3.reshape(5,4)

In [87]:
n3

array([[29, 25, 14, 84],
       [35, 93, 11, 84],
       [74, 35, 65, 53],
       [42, 50, 49,  9],
       [90, 87, 36, 97]])

In [88]:
n3[4]

array([90, 87, 36, 97])

In [89]:
n3[3,0]

42

In [90]:
n3[:2]

array([[29, 25, 14, 84],
       [35, 93, 11, 84]])

In [91]:
n3[:,2:4]

array([[14, 84],
       [11, 84],
       [65, 53],
       [49,  9],
       [36, 97]])

In [92]:
n3[:,(2,3)]

array([[14, 84],
       [11, 84],
       [65, 53],
       [49,  9],
       [36, 97]])

In [106]:
n3[2:4,2:4]

array([[65, 53],
       [49,  9]])

In [107]:
n4 =np.arange(1,7)

In [108]:
n4

array([1, 2, 3, 4, 5, 6])

In [109]:
n4s = n4.view()

In [110]:
n4s

array([1, 2, 3, 4, 5, 6])

In [111]:
n4[3]*=7 

In [112]:
n4

array([ 1,  2,  3, 28,  5,  6])

In [113]:
n4s

array([ 1,  2,  3, 28,  5,  6])

In [116]:
n4s[2] +=5

In [117]:
n4s

array([ 6,  7, 13, 33, 10, 11])

In [118]:
n4

array([ 6,  7, 13, 33, 10, 11])

In [119]:
n4dc = n4.copy()

In [120]:
n4dc

array([ 6,  7, 13, 33, 10, 11])

In [121]:
n4dc[1] -=5

In [122]:
n4dc

array([ 6,  2, 13, 33, 10, 11])

In [123]:
n4

array([ 6,  7, 13, 33, 10, 11])

In [124]:
n4s

array([ 6,  7, 13, 33, 10, 11])

In [125]:
n4s.dtype

dtype('int32')

In [126]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [127]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [128]:
listarray.dtype

dtype('int32')

In [129]:
listarray.size

9

In [130]:
listarray.shape

(3, 3)

In [131]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [134]:
zeros = np.zeros((2,5))

In [135]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [138]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [139]:
rng = np.arange(15)

In [140]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [163]:
lspace = np.linspace(1,16,6)

In [164]:
lspace

array([ 1.,  4.,  7., 10., 13., 16.])

In [165]:
emp = np.empty((4,6))

In [166]:
emp

array([[9.91471694e-312, 7.41098469e-322, 0.00000000e+000,
        0.00000000e+000, 1.06811354e-306, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 6.19319847e-071,
        1.03080552e+136, 6.01347002e-154, 9.63125397e+140],
       [6.01347002e-154, 8.44253652e-053, 6.01391519e-154,
        1.17999384e-095, 1.81148490e-152, 2.63753656e-061],
       [1.95361344e-109, 2.86752281e+161, 2.78225500e+296,
        9.80058441e+252, 1.23971686e+224, 6.80083175e-310]])

In [167]:
emp_like = np.empty_like(lspace)

In [168]:
emp_like

array([ 1.,  4.,  7., 10., 13., 16.])

In [169]:
id = np.identity(45)

In [170]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [171]:
id.shape

(45, 45)

In [172]:
arr = np.arange(99)

In [173]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [174]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [176]:
arr = arr.ravel()

In [178]:
arr.shape

(99,)

In [179]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [180]:
ar = np.array(x)

In [181]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [182]:
ar.sum(axis=0)

array([12,  8,  9])

In [183]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [184]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [185]:
ar.flat

In [186]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [187]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [189]:
ar.ndim

2

In [190]:
ar.nbytes

36

In [191]:
ar.size

9

In [192]:
one =np.array([1,3,4,634,2])

In [193]:
one.argmax()

3

In [194]:
one.argmin()

0

In [195]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [196]:
one.ravel()

array([  1,   3,   4, 634,   2])

In [197]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [198]:
ar2 = np.array([[1,4,1],
               [4,0,6],
               [8,1,0]])

In [199]:
ar2

array([[1, 4, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [200]:
ar + ar2

array([[ 2,  6,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [201]:
ar*ar2

array([[ 1,  8,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [202]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [203]:
ar.sum()

29

In [204]:
ar.max()

7

In [205]:
ar.min()

0

In [209]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [207]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [210]:
np.count_nonzero(ar)

8

In [211]:
import sys

In [213]:
py_ar = [0,4,55,2]

In [214]:
np_ar = np.array(py_ar)

In [215]:
np_ar

array([ 0,  4, 55,  2])

In [218]:
sys.getsizeof(1) *len(py_ar)

112

In [221]:
np_ar.itemsize*np_ar.size

16

## Keith Galli

### Basics

In [222]:
import numpy as np

In [224]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [225]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [226]:
a.ndim

1

In [227]:
b.ndim

2

In [228]:
#get shape
a.shape

(3,)

In [229]:
b.shape

(2, 3)

In [230]:
a.dtype

dtype('int32')

In [231]:
b.dtype

dtype('float64')

In [232]:
#get size
a.itemsize

4

In [233]:
b.itemsize

8

In [235]:
a.size

3

In [236]:
b.size

6

In [237]:
a.nbytes

12

In [238]:
b.nbytes

48

In [239]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [242]:
#Get a specific element [r,c]
a[1, 5]

13

In [243]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [244]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [246]:
# Getting a little more fancy [start index:end index:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [247]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [248]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [249]:
##3d example
b =np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [254]:
#work outside in
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [255]:
b[:,1,:] = [[9,9],[8,8]]

In [256]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different types of arrays

In [259]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [261]:
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [264]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [265]:
#Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [268]:
np.random.rand(4,2)

array([[0.56430386, 0.38986029],
       [0.43342228, 0.78290685],
       [0.98733575, 0.51422233],
       [0.22917356, 0.41298969]])

In [271]:
np.random.randint(7, size=(3,3))

array([[4, 0, 0],
       [1, 3, 6],
       [1, 4, 4]])

In [273]:
#The identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [278]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [279]:
e = np.ones((5,5))

In [280]:
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [285]:
z = np.zeros((3,3))

In [286]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [287]:
z[1,1] = 9

In [288]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [290]:
e[1:4,1:4] = z

In [291]:
e

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [292]:
### Be careful when copying da

In [293]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [296]:
b[0] = 100
print(b)

[[[100 100]
  [100 100]]

 [[  5   6]
  [  8   8]]]


### Mathematics

In [297]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [298]:
a+2

array([3, 4, 5, 6])

In [299]:
a-2

array([-1,  0,  1,  2])

In [300]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [301]:
a*2

array([2, 4, 6, 8])

In [302]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [303]:
b = np.array([1,0,1,0])
a +b

array([2, 2, 4, 4])

In [304]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [306]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [309]:
####Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [310]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [311]:
c = np.identity(3)

In [312]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [313]:
np.linalg.det(c)

1.0

### Statistics

In [314]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [317]:
np.min(stats)

1

In [316]:
np.max(stats, axis=1)

array([3, 6])

### Reorganizing Arrays

In [319]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [324]:
after = before.reshape((2,2,2))

In [325]:
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [326]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [327]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [328]:
#Boolean Masking
q = np.array([1,2,3,4,5,6,7,8,9])
q[[1,2,8]]

array([2, 3, 9])

In [333]:
a = np.arange(1,31).reshape(6,5)

In [334]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [336]:
a[2:4,:2]

array([[11, 12],
       [16, 17]])

In [337]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [348]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])