##Numpy 

In [1]:
import numpy as np

In [12]:
N_array = np.array( [ [1,2,3,2],[5,6,7,8] ] )

In [13]:
N_array

array([[1, 2, 3, 2],
       [5, 6, 7, 8]])

In [8]:
N_array_1 = np.array([[2,4,16],[9,8,15]])

In [9]:
N_array_1

array([[ 2,  4, 16],
       [ 9,  8, 15]])

###Array and Features

In [14]:
int = np.array([[1,2,3 ,4],[5,6,7, 13]])

In [15]:
int

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 13]])

In [28]:
floats = np.array([0.0, 0.10,0.12,0.3,0.5 ,0.63])

In [29]:
floats

array([0.  , 0.1 , 0.12, 0.3 , 0.5 , 0.63])

In [30]:
int.ndim

2

In [31]:
 floats.ndim

1

In [32]:
int.shape

(2, 4)

In [33]:
  floats.shape

(6,)

In [34]:
int.size

8

In [36]:
floats.size

6

In [37]:
for row in int:
  print (row)

[1 2 3 4]
[ 5  6  7 13]


In [39]:
for i in int.flat:
  print(i)

1
2
3
4
5
6
7
13


In [40]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [43]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [49]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [50]:
np.linspace(0,50)

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [54]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [55]:
np.arange(1,31).reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [56]:
np.arange(1,31).reshape(4,6)

ValueError: ignored

In [58]:
np.random.randint(1,20,4)

array([4, 6, 6, 3])

In [62]:
rand_array = np.random.randint(1,100,15)

In [63]:
rand_array.sum()

752

In [64]:
rand_array.max()

94

In [66]:
rand_array.min()

14

In [67]:
rand_array.mean()

50.13333333333333

In [68]:
rand_array.std()

24.21257708070103

###Array Operators

In [72]:
number_1 = np.arange(1,10,2)
number_rand = np.random.randint(1,20,5)

In [73]:
number_1

array([1, 3, 5, 7, 9])

In [77]:
number_rand

array([18,  2,  7,  9, 12])

In [78]:
number_1 + number_rand

array([19,  5, 12, 16, 21])

In [79]:
number_1 * number_rand

array([ 18,   6,  35,  63, 108])

In [80]:
number_1/3

array([0.33333333, 1.        , 1.66666667, 2.33333333, 3.        ])

In [81]:
number_rand/3

array([6.        , 0.66666667, 2.33333333, 3.        , 4.        ])

In [82]:
np.sqrt(number_1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ])

In [83]:
np.sqrt(number_rand)

array([4.24264069, 1.41421356, 2.64575131, 3.        , 3.46410162])

In [84]:
s = np.arange(1,10,2)

In [85]:
d = np.arange(1,11,3)

In [86]:
s + d

ValueError: ignored

###Indexing and Slicing

In [87]:
ni = np.random.randint(1,30,8)

In [88]:
ni

array([12, 28, 28,  6, 24, 14, 20, 22])

In [89]:
ni[3]

6

In [90]:
ni[2:6]

array([28,  6, 24, 14])

In [91]:
ni[:3]

array([12, 28, 28])

In [92]:
ni_2 = np.arange(1,7)

In [93]:
ni_2 

array([1, 2, 3, 4, 5, 6])

In [94]:
ni_2 [:3] = 7

In [96]:
ni_2

array([7, 7, 7, 4, 5, 6])

In [97]:
ni_3 = np.random.randint(1,100,20)

In [98]:
ni_3

array([13, 82, 13, 98,  4,  2, 71, 70, 99, 29, 13, 55, 99, 48, 11, 38, 40,
       61, 74,  3])

In [99]:
ni_3 = ni_3.reshape(5,4)

In [100]:
ni_3

array([[13, 82, 13, 98],
       [ 4,  2, 71, 70],
       [99, 29, 13, 55],
       [99, 48, 11, 38],
       [40, 61, 74,  3]])

In [101]:
ni_3[4]

array([40, 61, 74,  3])

In [102]:
ni_3[3]

array([99, 48, 11, 38])

In [103]:
ni_3[3,0]

99

In [105]:
ni_3[:2]

array([[13, 82, 13, 98],
       [ 4,  2, 71, 70]])

In [106]:
ni_3[:,2:4]

array([[13, 98],
       [71, 70],
       [13, 55],
       [11, 38],
       [74,  3]])

In [108]:
ni_3[:,(2,3)]

array([[13, 98],
       [71, 70],
       [13, 55],
       [11, 38],
       [74,  3]])

In [111]:
ni_4 = np.arange(1,7)

In [112]:
ni_4

array([1, 2, 3, 4, 5, 6])

In [113]:
ni_4[4]*=4

In [114]:
ni_4

array([ 1,  2,  3,  4, 20,  6])

In [115]:
ni_4[2] +=5

In [116]:
ni_4

array([ 1,  2,  8,  4, 20,  6])

In [117]:
ni_4_dc = ni_4.copy()

In [118]:
ni_4_dc 

array([ 1,  2,  8,  4, 20,  6])

In [119]:
ni_4_dc[1] -=3

In [120]:
ni_4_dc

array([ 1, -1,  8,  4, 20,  6])

In [121]:
ni_4

array([ 1,  2,  8,  4, 20,  6])

###Numpy Excercise

In [122]:
arr_1 = np.random.randint(1,150,20)

In [124]:
arr_1

array([102, 145, 131,  85,  60,  36, 106, 109,  70,  36,  45,  21, 141,
        61,  20,  86,  36, 103, 114,   2])

In [125]:
arr_1.sum()

1509

In [126]:
arr_1.max()

145

In [127]:
arr_1.min()

2

In [128]:
arr_1.mean()

75.45

In [129]:
arr_2 = np.arange(1,60,3)

In [131]:
arr_2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58])

In [132]:
arr_2 + arr_1

array([103, 149, 138,  95,  73,  52, 125, 131,  95,  64,  76,  55, 178,
       101,  63, 132,  85, 155, 169,  60])

In [133]:
arr_1

array([102, 145, 131,  85,  60,  36, 106, 109,  70,  36,  45,  21, 141,
        61,  20,  86,  36, 103, 114,   2])

In [135]:
arr_1[10]

45

In [137]:
r_element = arr_1[np.random.randint(1,21,1)]

In [138]:
r_element

array([36])

In [139]:
index_value = np.where(arr_1 == r_element)

In [140]:
index_value

(array([ 5,  9, 16]),)

In [141]:
arr_2 = arr_1.reshape(4,5)

In [142]:
arr_2

array([[102, 145, 131,  85,  60],
       [ 36, 106, 109,  70,  36],
       [ 45,  21, 141,  61,  20],
       [ 86,  36, 103, 114,   2]])

In [143]:
arr_2[:,(1,4)]

array([[145,  60],
       [106,  36],
       [ 21,  20],
       [ 36,   2]])

In [146]:
arr_2a = np.pad(arr_2,pad_width= 1, mode = "constant", constant_values = 0)

In [147]:
arr_2a

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0, 102, 145, 131,  85,  60,   0],
       [  0,  36, 106, 109,  70,  36,   0],
       [  0,  45,  21, 141,  61,  20,   0],
       [  0,  86,  36, 103, 114,   2,   0],
       [  0,   0,   0,   0,   0,   0,   0]])

In [148]:
arr_5 = np.arange(1,101).reshape(10,10)

In [149]:
arr_5

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [150]:
arr_5[5:]

array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [151]:
arr_5[:5]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [152]:
arr_5[4:,5:]

array([[ 46,  47,  48,  49,  50],
       [ 56,  57,  58,  59,  60],
       [ 66,  67,  68,  69,  70],
       [ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [153]:
arr_5[2:5,4:7]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [154]:
arr_5

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [155]:
arr_5[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [156]:
arr_a = ((np.random.rand(15)*10).astype(int)).reshape(3,5)

TypeError: ignored

##Pandas

In [157]:
import pandas as pd

In [158]:
import numpy as np

In [160]:
p_series = pd.Series([7,11,19,113])

In [161]:
p_series

0      7
1     11
2     19
3    113
dtype: int64

In [162]:
p_series_2 = pd.Series(29,range(5))

In [163]:
p_series_2 

0    29
1    29
2    29
3    29
4    29
dtype: int64

In [164]:
p_series[3]

113

In [168]:
p_series_3 = pd.Series(np.random.randint(1,150,10))

In [169]:
p_series_3

0     10
1     61
2      4
3     54
4    148
5    137
6     30
7    112
8      6
9     80
dtype: int64

In [170]:
p_series_3.max()

148

In [171]:
p_series_3.min()

4

In [172]:
p_series_3.mean()

64.2

In [173]:
p_series_3.std()

53.840917938352845

In [174]:
p_series_3.describe()

count     10.000000
mean      64.200000
std       53.840918
min        4.000000
25%       15.000000
50%       57.500000
75%      104.000000
max      148.000000
dtype: float64

In [175]:
help

Type help() for interactive help, or help(object) for help about object.

In [179]:
p_series_3.head()

0     10
1     61
2      4
3     54
4    148
dtype: int64

In [180]:
p_series_3.head(2)

0    10
1    61
dtype: int64

In [181]:
p_series_3.tail()

5    137
6     30
7    112
8      6
9     80
dtype: int64

In [182]:
p_series_3.tail(2)

8     6
9    80
dtype: int64

In [183]:
p_series_4 = pd.Series([5,13,23,29], index = ["Joe","William","Jack","Avarell"])

In [184]:
p_series_4

Joe         5
William    13
Jack       23
Avarell    29
dtype: int64

In [185]:
p_series_4['Jack']

23

In [186]:
p_series_4.Joe

5

In [187]:
p_series_d = pd.Series({"One":1,"Two":2,"Three":3,"Four":4,"Five":5})

In [188]:
p_series_d

One      1
Two      2
Three    3
Four     4
Five     5
dtype: int64

In [189]:
p_series_s = pd.Series(['Tom','Jerry',"Spike","Tyke","Nibbles","Quacker"])

In [190]:
p_series_s

0        Tom
1      Jerry
2      Spike
3       Tyke
4    Nibbles
5    Quacker
dtype: object

In [191]:
p_series_s.str.contains('e')

0    False
1     True
2     True
3     True
4     True
5     True
dtype: bool

In [192]:
p_series_s.str.upper()

0        TOM
1      JERRY
2      SPIKE
3       TYKE
4    NIBBLES
5    QUACKER
dtype: object

In [193]:
Data = [1,2,3,4,5,6,7]

In [194]:
Label =["apple","cherry","banana","orange","pear","melon"]

In [195]:
pd.Series(data = Data , index = Label)

apple     1
cherry    2
banana    3
orange    4
pear      5
melon     6
dtype: int64

In [199]:
sd_rw = pd.Series([70,63,150,45,33,35],["Chocolate","Bread","Biscuits","Potates(kg)","Carrots(kg)","Chips"])

In [200]:
sd_lw = pd.Series([45,51,90,67,44,13],["Chocolate","Bread","Biscuits","Potates(kg)","Carrots(kg)","Crackers"])

In [201]:
sd_lw

Chocolate      45
Bread          51
Biscuits       90
Potates(kg)    67
Carrots(kg)    44
Crackers       13
dtype: int64

In [202]:
sd_rw

Chocolate       70
Bread           63
Biscuits       150
Potates(kg)     45
Carrots(kg)     33
Chips           35
dtype: int64

In [203]:
sd_lw + sd_rw

Biscuits       240.0
Bread          114.0
Carrots(kg)     77.0
Chips            NaN
Chocolate      115.0
Crackers         NaN
Potates(kg)    112.0
dtype: float64